# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Power Coding
tagline:             '파워 코딩'
description:         '코딩은 언제나 힘차게'
url:                 http://SuperPowerCoding.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              JiHun Cho
  url:               http://SuperPowerCoding.github.io
  email:             deagalyang@gmail.com

# Custom vars
version:             1.0.0
